package ontomobile.phd.research;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Artefact <br>
 * @version generated on Tue Nov 26 14:33:00 GMT+00:00 2019 by umarriaz
 */

public interface Artefact extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Artefact-relation_with
     */
     
    /**
     * Gets all property values for the has_Artefact_relation_with property.<p>
     * 
     * @returns a collection of values for the has_Artefact_relation_with property.
     */
    Collection<? extends Artefact> getHas_Artefact_relation_with();

    /**
     * Checks if the class has a has_Artefact_relation_with property value.<p>
     * 
     * @return true if there is a has_Artefact_relation_with property value.
     */
    boolean hasHas_Artefact_relation_with();

    /**
     * Adds a has_Artefact_relation_with property value.<p>
     * 
     * @param newHas_Artefact_relation_with the has_Artefact_relation_with property value to be added
     */
    void addHas_Artefact_relation_with(Artefact newHas_Artefact_relation_with);

    /**
     * Removes a has_Artefact_relation_with property value.<p>
     * 
     * @param oldHas_Artefact_relation_with the has_Artefact_relation_with property value to be removed.
     */
    void removeHas_Artefact_relation_with(Artefact oldHas_Artefact_relation_with);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Date_Range
     */
     
    /**
     * Gets all property values for the has_Date_Range property.<p>
     * 
     * @returns a collection of values for the has_Date_Range property.
     */
    Collection<? extends Date_Range> getHas_Date_Range();

    /**
     * Checks if the class has a has_Date_Range property value.<p>
     * 
     * @return true if there is a has_Date_Range property value.
     */
    boolean hasHas_Date_Range();

    /**
     * Adds a has_Date_Range property value.<p>
     * 
     * @param newHas_Date_Range the has_Date_Range property value to be added
     */
    void addHas_Date_Range(Date_Range newHas_Date_Range);

    /**
     * Removes a has_Date_Range property value.<p>
     * 
     * @param oldHas_Date_Range the has_Date_Range property value to be removed.
     */
    void removeHas_Date_Range(Date_Range oldHas_Date_Range);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Form_Label
     */
     
    /**
     * Gets all property values for the has_Form_Label property.<p>
     * 
     * @returns a collection of values for the has_Form_Label property.
     */
    Collection<? extends Form_Label> getHas_Form_Label();

    /**
     * Checks if the class has a has_Form_Label property value.<p>
     * 
     * @return true if there is a has_Form_Label property value.
     */
    boolean hasHas_Form_Label();

    /**
     * Adds a has_Form_Label property value.<p>
     * 
     * @param newHas_Form_Label the has_Form_Label property value to be added
     */
    void addHas_Form_Label(Form_Label newHas_Form_Label);

    /**
     * Removes a has_Form_Label property value.<p>
     * 
     * @param oldHas_Form_Label the has_Form_Label property value to be removed.
     */
    void removeHas_Form_Label(Form_Label oldHas_Form_Label);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Form_Type
     */
     
    /**
     * Gets all property values for the has_Form_Type property.<p>
     * 
     * @returns a collection of values for the has_Form_Type property.
     */
    Collection<? extends Form_Type> getHas_Form_Type();

    /**
     * Checks if the class has a has_Form_Type property value.<p>
     * 
     * @return true if there is a has_Form_Type property value.
     */
    boolean hasHas_Form_Type();

    /**
     * Adds a has_Form_Type property value.<p>
     * 
     * @param newHas_Form_Type the has_Form_Type property value to be added
     */
    void addHas_Form_Type(Form_Type newHas_Form_Type);

    /**
     * Removes a has_Form_Type property value.<p>
     * 
     * @param oldHas_Form_Type the has_Form_Type property value to be removed.
     */
    void removeHas_Form_Type(Form_Type oldHas_Form_Type);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Function
     */
     
    /**
     * Gets all property values for the has_Function property.<p>
     * 
     * @returns a collection of values for the has_Function property.
     */
    Collection<? extends Function> getHas_Function();

    /**
     * Checks if the class has a has_Function property value.<p>
     * 
     * @return true if there is a has_Function property value.
     */
    boolean hasHas_Function();

    /**
     * Adds a has_Function property value.<p>
     * 
     * @param newHas_Function the has_Function property value to be added
     */
    void addHas_Function(Function newHas_Function);

    /**
     * Removes a has_Function property value.<p>
     * 
     * @param oldHas_Function the has_Function property value to be removed.
     */
    void removeHas_Function(Function oldHas_Function);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Inscription_OR_Stamp
     */
     
    /**
     * Gets all property values for the has_Inscription_OR_Stamp property.<p>
     * 
     * @returns a collection of values for the has_Inscription_OR_Stamp property.
     */
    Collection<? extends Inscription_OR_Stamp> getHas_Inscription_OR_Stamp();

    /**
     * Checks if the class has a has_Inscription_OR_Stamp property value.<p>
     * 
     * @return true if there is a has_Inscription_OR_Stamp property value.
     */
    boolean hasHas_Inscription_OR_Stamp();

    /**
     * Adds a has_Inscription_OR_Stamp property value.<p>
     * 
     * @param newHas_Inscription_OR_Stamp the has_Inscription_OR_Stamp property value to be added
     */
    void addHas_Inscription_OR_Stamp(Inscription_OR_Stamp newHas_Inscription_OR_Stamp);

    /**
     * Removes a has_Inscription_OR_Stamp property value.<p>
     * 
     * @param oldHas_Inscription_OR_Stamp the has_Inscription_OR_Stamp property value to be removed.
     */
    void removeHas_Inscription_OR_Stamp(Inscription_OR_Stamp oldHas_Inscription_OR_Stamp);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Latin_Descriptive_Label
     */
     
    /**
     * Gets all property values for the has_Latin_Descriptive_Label property.<p>
     * 
     * @returns a collection of values for the has_Latin_Descriptive_Label property.
     */
    Collection<? extends Latin_Descriptive_Label> getHas_Latin_Descriptive_Label();

    /**
     * Checks if the class has a has_Latin_Descriptive_Label property value.<p>
     * 
     * @return true if there is a has_Latin_Descriptive_Label property value.
     */
    boolean hasHas_Latin_Descriptive_Label();

    /**
     * Adds a has_Latin_Descriptive_Label property value.<p>
     * 
     * @param newHas_Latin_Descriptive_Label the has_Latin_Descriptive_Label property value to be added
     */
    void addHas_Latin_Descriptive_Label(Latin_Descriptive_Label newHas_Latin_Descriptive_Label);

    /**
     * Removes a has_Latin_Descriptive_Label property value.<p>
     * 
     * @param oldHas_Latin_Descriptive_Label the has_Latin_Descriptive_Label property value to be removed.
     */
    void removeHas_Latin_Descriptive_Label(Latin_Descriptive_Label oldHas_Latin_Descriptive_Label);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Stratigraphic_Relation_with
     */
     
    /**
     * Gets all property values for the has_Stratigraphic_Relation_with property.<p>
     * 
     * @returns a collection of values for the has_Stratigraphic_Relation_with property.
     */
    Collection<? extends WrappedIndividual> getHas_Stratigraphic_Relation_with();

    /**
     * Checks if the class has a has_Stratigraphic_Relation_with property value.<p>
     * 
     * @return true if there is a has_Stratigraphic_Relation_with property value.
     */
    boolean hasHas_Stratigraphic_Relation_with();

    /**
     * Adds a has_Stratigraphic_Relation_with property value.<p>
     * 
     * @param newHas_Stratigraphic_Relation_with the has_Stratigraphic_Relation_with property value to be added
     */
    void addHas_Stratigraphic_Relation_with(WrappedIndividual newHas_Stratigraphic_Relation_with);

    /**
     * Removes a has_Stratigraphic_Relation_with property value.<p>
     * 
     * @param oldHas_Stratigraphic_Relation_with the has_Stratigraphic_Relation_with property value to be removed.
     */
    void removeHas_Stratigraphic_Relation_with(WrappedIndividual oldHas_Stratigraphic_Relation_with);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_associated_with
     */
     
    /**
     * Gets all property values for the is_associated_with property.<p>
     * 
     * @returns a collection of values for the is_associated_with property.
     */
    Collection<? extends WrappedIndividual> getIs_associated_with();

    /**
     * Checks if the class has a is_associated_with property value.<p>
     * 
     * @return true if there is a is_associated_with property value.
     */
    boolean hasIs_associated_with();

    /**
     * Adds a is_associated_with property value.<p>
     * 
     * @param newIs_associated_with the is_associated_with property value to be added
     */
    void addIs_associated_with(WrappedIndividual newIs_associated_with);

    /**
     * Removes a is_associated_with property value.<p>
     * 
     * @param oldIs_associated_with the is_associated_with property value to be removed.
     */
    void removeIs_associated_with(WrappedIndividual oldIs_associated_with);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_associated_with_Phase
     */
     
    /**
     * Gets all property values for the is_associated_with_Phase property.<p>
     * 
     * @returns a collection of values for the is_associated_with_Phase property.
     */
    Collection<? extends WrappedIndividual> getIs_associated_with_Phase();

    /**
     * Checks if the class has a is_associated_with_Phase property value.<p>
     * 
     * @return true if there is a is_associated_with_Phase property value.
     */
    boolean hasIs_associated_with_Phase();

    /**
     * Adds a is_associated_with_Phase property value.<p>
     * 
     * @param newIs_associated_with_Phase the is_associated_with_Phase property value to be added
     */
    void addIs_associated_with_Phase(WrappedIndividual newIs_associated_with_Phase);

    /**
     * Removes a is_associated_with_Phase property value.<p>
     * 
     * @param oldIs_associated_with_Phase the is_associated_with_Phase property value to be removed.
     */
    void removeIs_associated_with_Phase(WrappedIndividual oldIs_associated_with_Phase);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_fragmented_in
     */
     
    /**
     * Gets all property values for the is_fragmented_in property.<p>
     * 
     * @returns a collection of values for the is_fragmented_in property.
     */
    Collection<? extends Fragment> getIs_fragmented_in();

    /**
     * Checks if the class has a is_fragmented_in property value.<p>
     * 
     * @return true if there is a is_fragmented_in property value.
     */
    boolean hasIs_fragmented_in();

    /**
     * Adds a is_fragmented_in property value.<p>
     * 
     * @param newIs_fragmented_in the is_fragmented_in property value to be added
     */
    void addIs_fragmented_in(Fragment newIs_fragmented_in);

    /**
     * Removes a is_fragmented_in property value.<p>
     * 
     * @param oldIs_fragmented_in the is_fragmented_in property value to be removed.
     */
    void removeIs_fragmented_in(Fragment oldIs_fragmented_in);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_made_from
     */
     
    /**
     * Gets all property values for the is_made_from property.<p>
     * 
     * @returns a collection of values for the is_made_from property.
     */
    Collection<? extends Material> getIs_made_from();

    /**
     * Checks if the class has a is_made_from property value.<p>
     * 
     * @return true if there is a is_made_from property value.
     */
    boolean hasIs_made_from();

    /**
     * Adds a is_made_from property value.<p>
     * 
     * @param newIs_made_from the is_made_from property value to be added
     */
    void addIs_made_from(Material newIs_made_from);

    /**
     * Removes a is_made_from property value.<p>
     * 
     * @param oldIs_made_from the is_made_from property value to be removed.
     */
    void removeIs_made_from(Material oldIs_made_from);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_overlain_by
     */
     
    /**
     * Gets all property values for the is_overlain_by property.<p>
     * 
     * @returns a collection of values for the is_overlain_by property.
     */
    Collection<? extends WrappedIndividual> getIs_overlain_by();

    /**
     * Checks if the class has a is_overlain_by property value.<p>
     * 
     * @return true if there is a is_overlain_by property value.
     */
    boolean hasIs_overlain_by();

    /**
     * Adds a is_overlain_by property value.<p>
     * 
     * @param newIs_overlain_by the is_overlain_by property value to be added
     */
    void addIs_overlain_by(WrappedIndividual newIs_overlain_by);

    /**
     * Removes a is_overlain_by property value.<p>
     * 
     * @param oldIs_overlain_by the is_overlain_by property value to be removed.
     */
    void removeIs_overlain_by(WrappedIndividual oldIs_overlain_by);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_part_of
     */
     
    /**
     * Gets all property values for the is_part_of property.<p>
     * 
     * @returns a collection of values for the is_part_of property.
     */
    Collection<? extends WrappedIndividual> getIs_part_of();

    /**
     * Checks if the class has a is_part_of property value.<p>
     * 
     * @return true if there is a is_part_of property value.
     */
    boolean hasIs_part_of();

    /**
     * Adds a is_part_of property value.<p>
     * 
     * @param newIs_part_of the is_part_of property value to be added
     */
    void addIs_part_of(WrappedIndividual newIs_part_of);

    /**
     * Removes a is_part_of property value.<p>
     * 
     * @param oldIs_part_of the is_part_of property value to be removed.
     */
    void removeIs_part_of(WrappedIndividual oldIs_part_of);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_part_of_spatial
     */
     
    /**
     * Gets all property values for the is_part_of_spatial property.<p>
     * 
     * @returns a collection of values for the is_part_of_spatial property.
     */
    Collection<? extends WrappedIndividual> getIs_part_of_spatial();

    /**
     * Checks if the class has a is_part_of_spatial property value.<p>
     * 
     * @return true if there is a is_part_of_spatial property value.
     */
    boolean hasIs_part_of_spatial();

    /**
     * Adds a is_part_of_spatial property value.<p>
     * 
     * @param newIs_part_of_spatial the is_part_of_spatial property value to be added
     */
    void addIs_part_of_spatial(WrappedIndividual newIs_part_of_spatial);

    /**
     * Removes a is_part_of_spatial property value.<p>
     * 
     * @param oldIs_part_of_spatial the is_part_of_spatial property value to be removed.
     */
    void removeIs_part_of_spatial(WrappedIndividual oldIs_part_of_spatial);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_part_of_temporal
     */
     
    /**
     * Gets all property values for the is_part_of_temporal property.<p>
     * 
     * @returns a collection of values for the is_part_of_temporal property.
     */
    Collection<? extends WrappedIndividual> getIs_part_of_temporal();

    /**
     * Checks if the class has a is_part_of_temporal property value.<p>
     * 
     * @return true if there is a is_part_of_temporal property value.
     */
    boolean hasIs_part_of_temporal();

    /**
     * Adds a is_part_of_temporal property value.<p>
     * 
     * @param newIs_part_of_temporal the is_part_of_temporal property value to be added
     */
    void addIs_part_of_temporal(WrappedIndividual newIs_part_of_temporal);

    /**
     * Removes a is_part_of_temporal property value.<p>
     * 
     * @param oldIs_part_of_temporal the is_part_of_temporal property value to be removed.
     */
    void removeIs_part_of_temporal(WrappedIndividual oldIs_part_of_temporal);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_subset_of
     */
     
    /**
     * Gets all property values for the is_subset_of property.<p>
     * 
     * @returns a collection of values for the is_subset_of property.
     */
    Collection<? extends WrappedIndividual> getIs_subset_of();

    /**
     * Checks if the class has a is_subset_of property value.<p>
     * 
     * @return true if there is a is_subset_of property value.
     */
    boolean hasIs_subset_of();

    /**
     * Adds a is_subset_of property value.<p>
     * 
     * @param newIs_subset_of the is_subset_of property value to be added
     */
    void addIs_subset_of(WrappedIndividual newIs_subset_of);

    /**
     * Removes a is_subset_of property value.<p>
     * 
     * @param oldIs_subset_of the is_subset_of property value to be removed.
     */
    void removeIs_subset_of(WrappedIndividual oldIs_subset_of);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_superset_of
     */
     
    /**
     * Gets all property values for the is_superset_of property.<p>
     * 
     * @returns a collection of values for the is_superset_of property.
     */
    Collection<? extends WrappedIndividual> getIs_superset_of();

    /**
     * Checks if the class has a is_superset_of property value.<p>
     * 
     * @return true if there is a is_superset_of property value.
     */
    boolean hasIs_superset_of();

    /**
     * Adds a is_superset_of property value.<p>
     * 
     * @param newIs_superset_of the is_superset_of property value to be added
     */
    void addIs_superset_of(WrappedIndividual newIs_superset_of);

    /**
     * Removes a is_superset_of property value.<p>
     * 
     * @param oldIs_superset_of the is_superset_of property value to be removed.
     */
    void removeIs_superset_of(WrappedIndividual oldIs_superset_of);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#overlays
     */
     
    /**
     * Gets all property values for the overlays property.<p>
     * 
     * @returns a collection of values for the overlays property.
     */
    Collection<? extends WrappedIndividual> getOverlays();

    /**
     * Checks if the class has a overlays property value.<p>
     * 
     * @return true if there is a overlays property value.
     */
    boolean hasOverlays();

    /**
     * Adds a overlays property value.<p>
     * 
     * @param newOverlays the overlays property value to be added
     */
    void addOverlays(WrappedIndividual newOverlays);

    /**
     * Removes a overlays property value.<p>
     * 
     * @param oldOverlays the overlays property value to be removed.
     */
    void removeOverlays(WrappedIndividual oldOverlays);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_found_at_Site
     */
     
    /**
     * Gets all property values for the was_found_at_Site property.<p>
     * 
     * @returns a collection of values for the was_found_at_Site property.
     */
    Collection<? extends Site> getWas_found_at_Site();

    /**
     * Checks if the class has a was_found_at_Site property value.<p>
     * 
     * @return true if there is a was_found_at_Site property value.
     */
    boolean hasWas_found_at_Site();

    /**
     * Adds a was_found_at_Site property value.<p>
     * 
     * @param newWas_found_at_Site the was_found_at_Site property value to be added
     */
    void addWas_found_at_Site(Site newWas_found_at_Site);

    /**
     * Removes a was_found_at_Site property value.<p>
     * 
     * @param oldWas_found_at_Site the was_found_at_Site property value to be removed.
     */
    void removeWas_found_at_Site(Site oldWas_found_at_Site);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_found_in_Archaeological_Context
     */
     
    /**
     * Gets all property values for the was_found_in_Archaeological_Context property.<p>
     * 
     * @returns a collection of values for the was_found_in_Archaeological_Context property.
     */
    Collection<? extends Archaeological_Context> getWas_found_in_Archaeological_Context();

    /**
     * Checks if the class has a was_found_in_Archaeological_Context property value.<p>
     * 
     * @return true if there is a was_found_in_Archaeological_Context property value.
     */
    boolean hasWas_found_in_Archaeological_Context();

    /**
     * Adds a was_found_in_Archaeological_Context property value.<p>
     * 
     * @param newWas_found_in_Archaeological_Context the was_found_in_Archaeological_Context property value to be added
     */
    void addWas_found_in_Archaeological_Context(Archaeological_Context newWas_found_in_Archaeological_Context);

    /**
     * Removes a was_found_in_Archaeological_Context property value.<p>
     * 
     * @param oldWas_found_in_Archaeological_Context the was_found_in_Archaeological_Context property value to be removed.
     */
    void removeWas_found_in_Archaeological_Context(Archaeological_Context oldWas_found_in_Archaeological_Context);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_made_by
     */
     
    /**
     * Gets all property values for the was_made_by property.<p>
     * 
     * @returns a collection of values for the was_made_by property.
     */
    Collection<? extends Maker> getWas_made_by();

    /**
     * Checks if the class has a was_made_by property value.<p>
     * 
     * @return true if there is a was_made_by property value.
     */
    boolean hasWas_made_by();

    /**
     * Adds a was_made_by property value.<p>
     * 
     * @param newWas_made_by the was_made_by property value to be added
     */
    void addWas_made_by(Maker newWas_made_by);

    /**
     * Removes a was_made_by property value.<p>
     * 
     * @param oldWas_made_by the was_made_by property value to be removed.
     */
    void removeWas_made_by(Maker oldWas_made_by);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_produced_at
     */
     
    /**
     * Gets all property values for the was_produced_at property.<p>
     * 
     * @returns a collection of values for the was_produced_at property.
     */
    Collection<? extends Production_Centre> getWas_produced_at();

    /**
     * Checks if the class has a was_produced_at property value.<p>
     * 
     * @return true if there is a was_produced_at property value.
     */
    boolean hasWas_produced_at();

    /**
     * Adds a was_produced_at property value.<p>
     * 
     * @param newWas_produced_at the was_produced_at property value to be added
     */
    void addWas_produced_at(Production_Centre newWas_produced_at);

    /**
     * Removes a was_produced_at property value.<p>
     * 
     * @param oldWas_produced_at the was_produced_at property value to be removed.
     */
    void removeWas_produced_at(Production_Centre oldWas_produced_at);


    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Current_Location
     */
     
    /**
     * Gets all property values for the Current_Location property.<p>
     * 
     * @returns a collection of values for the Current_Location property.
     */
    Collection<? extends String> getCurrent_Location();

    /**
     * Checks if the class has a Current_Location property value.<p>
     * 
     * @return true if there is a Current_Location property value.
     */
    boolean hasCurrent_Location();

    /**
     * Adds a Current_Location property value.<p>
     * 
     * @param newCurrent_Location the Current_Location property value to be added
     */
    void addCurrent_Location(String newCurrent_Location);

    /**
     * Removes a Current_Location property value.<p>
     * 
     * @param oldCurrent_Location the Current_Location property value to be removed.
     */
    void removeCurrent_Location(String oldCurrent_Location);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#associated_Emperor
     */
     
    /**
     * Gets all property values for the associated_Emperor property.<p>
     * 
     * @returns a collection of values for the associated_Emperor property.
     */
    Collection<? extends String> getAssociated_Emperor();

    /**
     * Checks if the class has a associated_Emperor property value.<p>
     * 
     * @return true if there is a associated_Emperor property value.
     */
    boolean hasAssociated_Emperor();

    /**
     * Adds a associated_Emperor property value.<p>
     * 
     * @param newAssociated_Emperor the associated_Emperor property value to be added
     */
    void addAssociated_Emperor(String newAssociated_Emperor);
    void addrestoration_evidence(String restoration_evidence);

    /**
     * Removes a associated_Emperor property value.<p>
     * 
     * @param oldAssociated_Emperor the associated_Emperor property value to be removed.
     */
    void removeAssociated_Emperor(String oldAssociated_Emperor);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Base_Diameter
     */
     
    /**
     * Gets all property values for the has_Base_Diameter property.<p>
     * 
     * @returns a collection of values for the has_Base_Diameter property.
     */
    Collection<? extends Float> getHas_Base_Diameter();

    /**
     * Checks if the class has a has_Base_Diameter property value.<p>
     * 
     * @return true if there is a has_Base_Diameter property value.
     */
    boolean hasHas_Base_Diameter();

    /**
     * Adds a has_Base_Diameter property value.<p>
     * 
     * @param newHas_Base_Diameter the has_Base_Diameter property value to be added
     */
    void addHas_Base_Diameter(Float newHas_Base_Diameter);

    /**
     * Removes a has_Base_Diameter property value.<p>
     * 
     * @param oldHas_Base_Diameter the has_Base_Diameter property value to be removed.
     */
    void removeHas_Base_Diameter(Float oldHas_Base_Diameter);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Base_Ring_Diameter
     */
     
    /**
     * Gets all property values for the has_Base_Ring_Diameter property.<p>
     * 
     * @returns a collection of values for the has_Base_Ring_Diameter property.
     */
    Collection<? extends Float> getHas_Base_Ring_Diameter();

    /**
     * Checks if the class has a has_Base_Ring_Diameter property value.<p>
     * 
     * @return true if there is a has_Base_Ring_Diameter property value.
     */
    boolean hasHas_Base_Ring_Diameter();

    /**
     * Adds a has_Base_Ring_Diameter property value.<p>
     * 
     * @param newHas_Base_Ring_Diameter the has_Base_Ring_Diameter property value to be added
     */
    void addHas_Base_Ring_Diameter(Float newHas_Base_Ring_Diameter);

    /**
     * Removes a has_Base_Ring_Diameter property value.<p>
     * 
     * @param oldHas_Base_Ring_Diameter the has_Base_Ring_Diameter property value to be removed.
     */
    void removeHas_Base_Ring_Diameter(Float oldHas_Base_Ring_Diameter);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Building_Phase_GIS_code
     */
     
    /**
     * Gets all property values for the has_Building_Phase_GIS_code property.<p>
     * 
     * @returns a collection of values for the has_Building_Phase_GIS_code property.
     */
    Collection<? extends String> getHas_Building_Phase_GIS_code();

    /**
     * Checks if the class has a has_Building_Phase_GIS_code property value.<p>
     * 
     * @return true if there is a has_Building_Phase_GIS_code property value.
     */
    boolean hasHas_Building_Phase_GIS_code();

    /**
     * Adds a has_Building_Phase_GIS_code property value.<p>
     * 
     * @param newHas_Building_Phase_GIS_code the has_Building_Phase_GIS_code property value to be added
     */
    void addHas_Building_Phase_GIS_code(String newHas_Building_Phase_GIS_code);

    /**
     * Removes a has_Building_Phase_GIS_code property value.<p>
     * 
     * @param oldHas_Building_Phase_GIS_code the has_Building_Phase_GIS_code property value to be removed.
     */
    void removeHas_Building_Phase_GIS_code(String oldHas_Building_Phase_GIS_code);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Catalogue_Number
     */
     
    /**
     * Gets all property values for the has_Catalogue_Number property.<p>
     * 
     * @returns a collection of values for the has_Catalogue_Number property.
     */
    Collection<? extends String> getHas_Catalogue_Number();

    /**
     * Checks if the class has a has_Catalogue_Number property value.<p>
     * 
     * @return true if there is a has_Catalogue_Number property value.
     */
    boolean hasHas_Catalogue_Number();

    /**
     * Adds a has_Catalogue_Number property value.<p>
     * 
     * @param newHas_Catalogue_Number the has_Catalogue_Number property value to be added
     */
    void addHas_Catalogue_Number(String newHas_Catalogue_Number);

    /**
     * Removes a has_Catalogue_Number property value.<p>
     * 
     * @param oldHas_Catalogue_Number the has_Catalogue_Number property value to be removed.
     */
    void removeHas_Catalogue_Number(String oldHas_Catalogue_Number);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Decoration
     */
     
    /**
     * Gets all property values for the has_Decoration property.<p>
     * 
     * @returns a collection of values for the has_Decoration property.
     */
    Collection<? extends String> getHas_Decoration();

    /**
     * Checks if the class has a has_Decoration property value.<p>
     * 
     * @return true if there is a has_Decoration property value.
     */
    boolean hasHas_Decoration();

    /**
     * Adds a has_Decoration property value.<p>
     * 
     * @param newHas_Decoration the has_Decoration property value to be added
     */
    void addHas_Decoration(String newHas_Decoration);

    /**
     * Removes a has_Decoration property value.<p>
     * 
     * @param oldHas_Decoration the has_Decoration property value to be removed.
     */
    void removeHas_Decoration(String oldHas_Decoration);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description
     */
     
    /**
     * Gets all property values for the has_Description property.<p>
     * 
     * @returns a collection of values for the has_Description property.
     */
    Collection<? extends String> getHas_Description();

    /**
     * Checks if the class has a has_Description property value.<p>
     * 
     * @return true if there is a has_Description property value.
     */
    boolean hasHas_Description();

    /**
     * Adds a has_Description property value.<p>
     * 
     * @param newHas_Description the has_Description property value to be added
     */
    void addHas_Description(String newHas_Description);

    /**
     * Removes a has_Description property value.<p>
     * 
     * @param oldHas_Description the has_Description property value to be removed.
     */
    void removeHas_Description(String oldHas_Description);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description_Location
     */
     
    /**
     * Gets all property values for the has_Description_Location property.<p>
     * 
     * @returns a collection of values for the has_Description_Location property.
     */
    Collection<? extends String> getHas_Description_Location();

    /**
     * Checks if the class has a has_Description_Location property value.<p>
     * 
     * @return true if there is a has_Description_Location property value.
     */
    boolean hasHas_Description_Location();

    /**
     * Adds a has_Description_Location property value.<p>
     * 
     * @param newHas_Description_Location the has_Description_Location property value to be added
     */
    void addHas_Description_Location(String newHas_Description_Location);

    /**
     * Removes a has_Description_Location property value.<p>
     * 
     * @param oldHas_Description_Location the has_Description_Location property value to be removed.
     */
    void removeHas_Description_Location(String oldHas_Description_Location);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description_Material
     */
     
    /**
     * Gets all property values for the has_Description_Material property.<p>
     * 
     * @returns a collection of values for the has_Description_Material property.
     */
    Collection<? extends String> getHas_Description_Material();

    /**
     * Checks if the class has a has_Description_Material property value.<p>
     * 
     * @return true if there is a has_Description_Material property value.
     */
    boolean hasHas_Description_Material();

    /**
     * Adds a has_Description_Material property value.<p>
     * 
     * @param newHas_Description_Material the has_Description_Material property value to be added
     */
    void addHas_Description_Material(String newHas_Description_Material);

    /**
     * Removes a has_Description_Material property value.<p>
     * 
     * @param oldHas_Description_Material the has_Description_Material property value to be removed.
     */
    void removeHas_Description_Material(String oldHas_Description_Material);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description_preservation
     */
     
    /**
     * Gets all property values for the has_Description_preservation property.<p>
     * 
     * @returns a collection of values for the has_Description_preservation property.
     */
    Collection<? extends String> getHas_Description_preservation();

    /**
     * Checks if the class has a has_Description_preservation property value.<p>
     * 
     * @return true if there is a has_Description_preservation property value.
     */
    boolean hasHas_Description_preservation();

    /**
     * Adds a has_Description_preservation property value.<p>
     * 
     * @param newHas_Description_preservation the has_Description_preservation property value to be added
     */
    void addHas_Description_preservation(String newHas_Description_preservation);

    /**
     * Removes a has_Description_preservation property value.<p>
     * 
     * @param oldHas_Description_preservation the has_Description_preservation property value to be removed.
     */
    void removeHas_Description_preservation(String oldHas_Description_preservation);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Diameter_other
     */
     
    /**
     * Gets all property values for the has_Diameter_other property.<p>
     * 
     * @returns a collection of values for the has_Diameter_other property.
     */
    Collection<? extends Float> getHas_Diameter_other();

    /**
     * Checks if the class has a has_Diameter_other property value.<p>
     * 
     * @return true if there is a has_Diameter_other property value.
     */
    boolean hasHas_Diameter_other();

    /**
     * Adds a has_Diameter_other property value.<p>
     * 
     * @param newHas_Diameter_other the has_Diameter_other property value to be added
     */
    void addHas_Diameter_other(Float newHas_Diameter_other);

    /**
     * Removes a has_Diameter_other property value.<p>
     * 
     * @param oldHas_Diameter_other the has_Diameter_other property value to be removed.
     */
    void removeHas_Diameter_other(Float oldHas_Diameter_other);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Dimensions
     */
     
    /**
     * Gets all property values for the has_Dimensions property.<p>
     * 
     * @returns a collection of values for the has_Dimensions property.
     */
    Collection<? extends Float> getHas_Dimensions();

    /**
     * Checks if the class has a has_Dimensions property value.<p>
     * 
     * @return true if there is a has_Dimensions property value.
     */
    boolean hasHas_Dimensions();

    /**
     * Adds a has_Dimensions property value.<p>
     * 
     * @param newHas_Dimensions the has_Dimensions property value to be added
     */
    void addHas_Dimensions(Float newHas_Dimensions);

    /**
     * Removes a has_Dimensions property value.<p>
     * 
     * @param oldHas_Dimensions the has_Dimensions property value to be removed.
     */
    void removeHas_Dimensions(Float oldHas_Dimensions);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_GIS_code_information
     */
     
    /**
     * Gets all property values for the has_GIS_code_information property.<p>
     * 
     * @returns a collection of values for the has_GIS_code_information property.
     */
    Collection<? extends String> getHas_GIS_code_information();

    /**
     * Checks if the class has a has_GIS_code_information property value.<p>
     * 
     * @return true if there is a has_GIS_code_information property value.
     */
    boolean hasHas_GIS_code_information();

    /**
     * Adds a has_GIS_code_information property value.<p>
     * 
     * @param newHas_GIS_code_information the has_GIS_code_information property value to be added
     */
    void addHas_GIS_code_information(String newHas_GIS_code_information);

    /**
     * Removes a has_GIS_code_information property value.<p>
     * 
     * @param oldHas_GIS_code_information the has_GIS_code_information property value to be removed.
     */
    void removeHas_GIS_code_information(String oldHas_GIS_code_information);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Glaze
     */
     
    /**
     * Gets all property values for the has_Glaze property.<p>
     * 
     * @returns a collection of values for the has_Glaze property.
     */
    Collection<? extends String> getHas_Glaze();

    /**
     * Checks if the class has a has_Glaze property value.<p>
     * 
     * @return true if there is a has_Glaze property value.
     */
    boolean hasHas_Glaze();

    /**
     * Adds a has_Glaze property value.<p>
     * 
     * @param newHas_Glaze the has_Glaze property value to be added
     */
    void addHas_Glaze(String newHas_Glaze);

    /**
     * Removes a has_Glaze property value.<p>
     * 
     * @param oldHas_Glaze the has_Glaze property value to be removed.
     */
    void removeHas_Glaze(String oldHas_Glaze);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Height
     */
     
    /**
     * Gets all property values for the has_Height property.<p>
     * 
     * @returns a collection of values for the has_Height property.
     */
    Collection<? extends Float> getHas_Height();

    /**
     * Checks if the class has a has_Height property value.<p>
     * 
     * @return true if there is a has_Height property value.
     */
    boolean hasHas_Height();

    /**
     * Adds a has_Height property value.<p>
     * 
     * @param newHas_Height the has_Height property value to be added
     */
    void addHas_Height(Float newHas_Height);

    /**
     * Removes a has_Height property value.<p>
     * 
     * @param oldHas_Height the has_Height property value to be removed.
     */
    void removeHas_Height(Float oldHas_Height);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Image_URL
     */
     
    /**
     * Gets all property values for the has_Image_URL property.<p>
     * 
     * @returns a collection of values for the has_Image_URL property.
     */
    Collection<? extends String> getHas_Image_URL();

    /**
     * Checks if the class has a has_Image_URL property value.<p>
     * 
     * @return true if there is a has_Image_URL property value.
     */
    boolean hasHas_Image_URL();

    /**
     * Adds a has_Image_URL property value.<p>
     * 
     * @param newHas_Image_URL the has_Image_URL property value to be added
     */
    void addHas_Image_URL(String newHas_Image_URL);

    /**
     * Removes a has_Image_URL property value.<p>
     * 
     * @param oldHas_Image_URL the has_Image_URL property value to be removed.
     */
    void removeHas_Image_URL(String oldHas_Image_URL);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Length
     */
     
    /**
     * Gets all property values for the has_Length property.<p>
     * 
     * @returns a collection of values for the has_Length property.
     */
    Collection<? extends Float> getHas_Length();

    /**
     * Checks if the class has a has_Length property value.<p>
     * 
     * @return true if there is a has_Length property value.
     */
    boolean hasHas_Length();

    /**
     * Adds a has_Length property value.<p>
     * 
     * @param newHas_Length the has_Length property value to be added
     */
    void addHas_Length(Float newHas_Length);

    /**
     * Removes a has_Length property value.<p>
     * 
     * @param oldHas_Length the has_Length property value to be removed.
     */
    void removeHas_Length(Float oldHas_Length);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Painted_Decoration
     */
     
    /**
     * Gets all property values for the has_Painted_Decoration property.<p>
     * 
     * @returns a collection of values for the has_Painted_Decoration property.
     */
    Collection<? extends String> getHas_Painted_Decoration();

    /**
     * Checks if the class has a has_Painted_Decoration property value.<p>
     * 
     * @return true if there is a has_Painted_Decoration property value.
     */
    boolean hasHas_Painted_Decoration();

    /**
     * Adds a has_Painted_Decoration property value.<p>
     * 
     * @param newHas_Painted_Decoration the has_Painted_Decoration property value to be added
     */
    void addHas_Painted_Decoration(String newHas_Painted_Decoration);

    /**
     * Removes a has_Painted_Decoration property value.<p>
     * 
     * @param oldHas_Painted_Decoration the has_Painted_Decoration property value to be removed.
     */
    void removeHas_Painted_Decoration(String oldHas_Painted_Decoration);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Provenance_Code
     */
     
    /**
     * Gets all property values for the has_Provenance_Code property.<p>
     * 
     * @returns a collection of values for the has_Provenance_Code property.
     */
    Collection<? extends String> getHas_Provenance_Code();

    /**
     * Checks if the class has a has_Provenance_Code property value.<p>
     * 
     * @return true if there is a has_Provenance_Code property value.
     */
    boolean hasHas_Provenance_Code();

    /**
     * Adds a has_Provenance_Code property value.<p>
     * 
     * @param newHas_Provenance_Code the has_Provenance_Code property value to be added
     */
    void addHas_Provenance_Code(String newHas_Provenance_Code);

    /**
     * Removes a has_Provenance_Code property value.<p>
     * 
     * @param oldHas_Provenance_Code the has_Provenance_Code property value to be removed.
     */
    void removeHas_Provenance_Code(String oldHas_Provenance_Code);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Reference
     */
     
    /**
     * Gets all property values for the has_Reference property.<p>
     * 
     * @returns a collection of values for the has_Reference property.
     */
    Collection<? extends String> getHas_Reference();

    /**
     * Checks if the class has a has_Reference property value.<p>
     * 
     * @return true if there is a has_Reference property value.
     */
    boolean hasHas_Reference();

    /**
     * Adds a has_Reference property value.<p>
     * 
     * @param newHas_Reference the has_Reference property value to be added
     */
    void addHas_Reference(String newHas_Reference);

    /**
     * Removes a has_Reference property value.<p>
     * 
     * @param oldHas_Reference the has_Reference property value to be removed.
     */
    void removeHas_Reference(String oldHas_Reference);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Relief_Decoration
     */
     
    /**
     * Gets all property values for the has_Relief_Decoration property.<p>
     * 
     * @returns a collection of values for the has_Relief_Decoration property.
     */
    Collection<? extends String> getHas_Relief_Decoration();

    /**
     * Checks if the class has a has_Relief_Decoration property value.<p>
     * 
     * @return true if there is a has_Relief_Decoration property value.
     */
    boolean hasHas_Relief_Decoration();

    /**
     * Adds a has_Relief_Decoration property value.<p>
     * 
     * @param newHas_Relief_Decoration the has_Relief_Decoration property value to be added
     */
    void addHas_Relief_Decoration(String newHas_Relief_Decoration);

    /**
     * Removes a has_Relief_Decoration property value.<p>
     * 
     * @param oldHas_Relief_Decoration the has_Relief_Decoration property value to be removed.
     */
    void removeHas_Relief_Decoration(String oldHas_Relief_Decoration);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Rim_Diameter
     */
     
    /**
     * Gets all property values for the has_Rim_Diameter property.<p>
     * 
     * @returns a collection of values for the has_Rim_Diameter property.
     */
    Collection<? extends Float> getHas_Rim_Diameter();

    /**
     * Checks if the class has a has_Rim_Diameter property value.<p>
     * 
     * @return true if there is a has_Rim_Diameter property value.
     */
    boolean hasHas_Rim_Diameter();

    /**
     * Adds a has_Rim_Diameter property value.<p>
     * 
     * @param rimFloat the has_Rim_Diameter property value to be added
     */
    void addHas_Rim_Diameter(Float rimFloat);

    /**
     * Removes a has_Rim_Diameter property value.<p>
     * 
     * @param oldHas_Rim_Diameter the has_Rim_Diameter property value to be removed.
     */
    void removeHas_Rim_Diameter(Float oldHas_Rim_Diameter);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Surface_Treatment
     */
     
    /**
     * Gets all property values for the has_Surface_Treatment property.<p>
     * 
     * @returns a collection of values for the has_Surface_Treatment property.
     */
    Collection<? extends String> getHas_Surface_Treatment();

    /**
     * Checks if the class has a has_Surface_Treatment property value.<p>
     * 
     * @return true if there is a has_Surface_Treatment property value.
     */
    boolean hasHas_Surface_Treatment();

    /**
     * Adds a has_Surface_Treatment property value.<p>
     * 
     * @param newHas_Surface_Treatment the has_Surface_Treatment property value to be added
     */
    void addHas_Surface_Treatment(String newHas_Surface_Treatment);

    /**
     * Removes a has_Surface_Treatment property value.<p>
     * 
     * @param oldHas_Surface_Treatment the has_Surface_Treatment property value to be removed.
     */
    void removeHas_Surface_Treatment(String oldHas_Surface_Treatment);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Thickness
     */
     
    /**
     * Gets all property values for the has_Thickness property.<p>
     * 
     * @returns a collection of values for the has_Thickness property.
     */
    Collection<? extends Float> getHas_Thickness();

    /**
     * Checks if the class has a has_Thickness property value.<p>
     * 
     * @return true if there is a has_Thickness property value.
     */
    boolean hasHas_Thickness();

    /**
     * Adds a has_Thickness property value.<p>
     * 
     * @param newHas_Thickness the has_Thickness property value to be added
     */
    void addHas_Thickness(Float newHas_Thickness);

    /**
     * Removes a has_Thickness property value.<p>
     * 
     * @param oldHas_Thickness the has_Thickness property value to be removed.
     */
    void removeHas_Thickness(Float oldHas_Thickness);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Use_Wear
     */
     
    /**
     * Gets all property values for the has_Use_Wear property.<p>
     * 
     * @returns a collection of values for the has_Use_Wear property.
     */
    Collection<? extends String> getHas_Use_Wear();

    /**
     * Checks if the class has a has_Use_Wear property value.<p>
     * 
     * @return true if there is a has_Use_Wear property value.
     */
    boolean hasHas_Use_Wear();

    /**
     * Adds a has_Use_Wear property value.<p>
     * 
     * @param newHas_Use_Wear the has_Use_Wear property value to be added
     */
    void addHas_Use_Wear(String newHas_Use_Wear);

    /**
     * Removes a has_Use_Wear property value.<p>
     * 
     * @param oldHas_Use_Wear the has_Use_Wear property value to be removed.
     */
    void removeHas_Use_Wear(String oldHas_Use_Wear);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_breadth
     */
     
    /**
     * Gets all property values for the has_breadth property.<p>
     * 
     * @returns a collection of values for the has_breadth property.
     */
    Collection<? extends Float> getHas_breadth();

    /**
     * Checks if the class has a has_breadth property value.<p>
     * 
     * @return true if there is a has_breadth property value.
     */
    boolean hasHas_breadth();

    /**
     * Adds a has_breadth property value.<p>
     * 
     * @param newHas_breadth the has_breadth property value to be added
     */
    void addHas_breadth(Float newHas_breadth);

    /**
     * Removes a has_breadth property value.<p>
     * 
     * @param oldHas_breadth the has_breadth property value to be removed.
     */
    void removeHas_breadth(Float oldHas_breadth);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_colour
     */
     
    /**
     * Gets all property values for the has_colour property.<p>
     * 
     * @returns a collection of values for the has_colour property.
     */
    Collection<? extends String> getHas_colour();

    /**
     * Checks if the class has a has_colour property value.<p>
     * 
     * @return true if there is a has_colour property value.
     */
    boolean hasHas_colour();

    /**
     * Adds a has_colour property value.<p>
     * 
     * @param newHas_colour the has_colour property value to be added
     */
    void addHas_colour(String newHas_colour);

    /**
     * Removes a has_colour property value.<p>
     * 
     * @param oldHas_colour the has_colour property value to be removed.
     */
    void removeHas_colour(String oldHas_colour);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_identity_Label
     */
     
    /**
     * Gets all property values for the has_identity_Label property.<p>
     * 
     * @returns a collection of values for the has_identity_Label property.
     */
    Collection<? extends String> getHas_identity_Label();

    /**
     * Checks if the class has a has_identity_Label property value.<p>
     * 
     * @return true if there is a has_identity_Label property value.
     */
    boolean hasHas_identity_Label();

    /**
     * Adds a has_identity_Label property value.<p>
     * 
     * @param newHas_identity_Label the has_identity_Label property value to be added
     */
    void addHas_identity_Label(String newHas_identity_Label);

    /**
     * Removes a has_identity_Label property value.<p>
     * 
     * @param oldHas_identity_Label the has_identity_Label property value to be removed.
     */
    void removeHas_identity_Label(String oldHas_identity_Label);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_preserved_Height
     */
     
    /**
     * Gets all property values for the has_preserved_Height property.<p>
     * 
     * @returns a collection of values for the has_preserved_Height property.
     */
    Collection<? extends Float> getHas_preserved_Height();

    /**
     * Checks if the class has a has_preserved_Height property value.<p>
     * 
     * @return true if there is a has_preserved_Height property value.
     */
    boolean hasHas_preserved_Height();

    /**
     * Adds a has_preserved_Height property value.<p>
     * 
     * @param newHas_preserved_Height the has_preserved_Height property value to be added
     */
    void addHas_preserved_Height(Float newHas_preserved_Height);

    /**
     * Removes a has_preserved_Height property value.<p>
     * 
     * @param oldHas_preserved_Height the has_preserved_Height property value to be removed.
     */
    void removeHas_preserved_Height(Float oldHas_preserved_Height);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_surrounding_material
     */
     
    /**
     * Gets all property values for the has_surrounding_material property.<p>
     * 
     * @returns a collection of values for the has_surrounding_material property.
     */
    Collection<? extends String> getHas_surrounding_material();

    /**
     * Checks if the class has a has_surrounding_material property value.<p>
     * 
     * @return true if there is a has_surrounding_material property value.
     */
    boolean hasHas_surrounding_material();

    /**
     * Adds a has_surrounding_material property value.<p>
     * 
     * @param newHas_surrounding_material the has_surrounding_material property value to be added
     */
    void addHas_surrounding_material(String newHas_surrounding_material);

    /**
     * Removes a has_surrounding_material property value.<p>
     * 
     * @param oldHas_surrounding_material the has_surrounding_material property value to be removed.
     */
    void removeHas_surrounding_material(String oldHas_surrounding_material);



    /* ***************************************************
     * Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_weight
     */
     
    /**
     * Gets all property values for the has_weight property.<p>
     * 
     * @returns a collection of values for the has_weight property.
     */
    Collection<? extends Float> getHas_weight();

    /**
     * Checks if the class has a has_weight property value.<p>
     * 
     * @return true if there is a has_weight property value.
     */
    boolean hasHas_weight();

    /**
     * Adds a has_weight property value.<p>
     * 
     * @param newHas_weight the has_weight property value to be added
     */
    void addHas_weight(Float newHas_weight);

    /**
     * Removes a has_weight property value.<p>
     * 
     * @param oldHas_weight the has_weight property value to be removed.
     */
    void removeHas_weight(Float oldHas_weight);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
