package ontomobile.phd.research;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Tue Nov 26 14:33:00 GMT+00:00 2019 by umarriaz
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#'Engobierte_und_tongrundige'_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENGOBIERTE_UND_TONGRUNDIGE_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_ENGOBIERTE_UND_TONGRUNDIGE_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#'Engobierte_und_tongrundige'_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Archaeological_Context
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARCHAEOLOGICAL_CONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_ARCHAEOLOGICAL_CONTEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Archaeological_Context"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Artefact
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTEFACT.<p>
     * 
     */
    public static final OWLClass CLASS_ARTEFACT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Artefact"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_III
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BERNHARD_GROUP_III.<p>
     * 
     */
    public static final OWLClass CLASS_BERNHARD_GROUP_III = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_III"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_IIIa
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BERNHARD_GROUP_IIIA.<p>
     * 
     */
    public static final OWLClass CLASS_BERNHARD_GROUP_IIIA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_IIIa"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_IIa
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BERNHARD_GROUP_IIA.<p>
     * 
     */
    public static final OWLClass CLASS_BERNHARD_GROUP_IIA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_IIa"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_IIb
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BERNHARD_GROUP_IIB.<p>
     * 
     */
    public static final OWLClass CLASS_BERNHARD_GROUP_IIB = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_IIb"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_IIc
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BERNHARD_GROUP_IIC.<p>
     * 
     */
    public static final OWLClass CLASS_BERNHARD_GROUP_IIC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_IIc"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_Ia
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BERNHARD_GROUP_IA.<p>
     * 
     */
    public static final OWLClass CLASS_BERNHARD_GROUP_IA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_Ia"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_Ib
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BERNHARD_GROUP_IB.<p>
     * 
     */
    public static final OWLClass CLASS_BERNHARD_GROUP_IB = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Bernhard_Group_Ib"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Blickweiler
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BLICKWEILER.<p>
     * 
     */
    public static final OWLClass CLASS_BLICKWEILER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Blickweiler"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Building
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUILDING.<p>
     * 
     */
    public static final OWLClass CLASS_BUILDING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Building"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Building_Phase
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUILDING_PHASE.<p>
     * 
     */
    public static final OWLClass CLASS_BUILDING_PHASE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Building_Phase"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Ceramic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CERAMIC.<p>
     * 
     */
    public static final OWLClass CLASS_CERAMIC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Ceramic"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Ceramic_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CERAMIC_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_CERAMIC_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Ceramic_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Ceramics_Production_Centre
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CERAMICS_PRODUCTION_CENTRE.<p>
     * 
     */
    public static final OWLClass CLASS_CERAMICS_PRODUCTION_CENTRE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Ceramics_Production_Centre"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Chemery
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHEMERY.<p>
     * 
     */
    public static final OWLClass CLASS_CHEMERY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Chemery"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Coarse_Ceramic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COARSE_CERAMIC.<p>
     * 
     */
    public static final OWLClass CLASS_COARSE_CERAMIC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Coarse_Ceramic"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Coarse_Ceramic_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COARSE_CERAMIC_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_COARSE_CERAMIC_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Coarse_Ceramic_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Coin_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COIN_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_COIN_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Coin_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Complex
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPLEX.<p>
     * 
     */
    public static final OWLClass CLASS_COMPLEX = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Complex"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Coordinates
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COORDINATES.<p>
     * 
     */
    public static final OWLClass CLASS_COORDINATES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Coordinates"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Curle_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CURLE_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_CURLE_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Curle_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Date_Range
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATE_RANGE.<p>
     * 
     */
    public static final OWLClass CLASS_DATE_RANGE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Date_Range"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Dragendorff_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DRAGENDORFF_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_DRAGENDORFF_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Dragendorff_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Drexel_I
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DREXEL_I.<p>
     * 
     */
    public static final OWLClass CLASS_DREXEL_I = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Drexel_I"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Drexel_III
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DREXEL_III.<p>
     * 
     */
    public static final OWLClass CLASS_DREXEL_III = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Drexel_III"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Drexel_IIa
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DREXEL_IIA.<p>
     * 
     */
    public static final OWLClass CLASS_DREXEL_IIA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Drexel_IIa"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Drexel_IIb
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DREXEL_IIB.<p>
     * 
     */
    public static final OWLClass CLASS_DREXEL_IIB = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Drexel_IIb"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#East_Gaul
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EAST_GAUL.<p>
     * 
     */
    public static final OWLClass CLASS_EAST_GAUL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#East_Gaul"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Eschweiler_Hof
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ESCHWEILER_HOF.<p>
     * 
     */
    public static final OWLClass CLASS_ESCHWEILER_HOF = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Eschweiler_Hof"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Fine_Ceramic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FINE_CERAMIC.<p>
     * 
     */
    public static final OWLClass CLASS_FINE_CERAMIC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Fine_Ceramic"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Fine_Ceramic_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FINE_CERAMIC_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_FINE_CERAMIC_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Fine_Ceramic_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Form_Label
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FORM_LABEL.<p>
     * 
     */
    public static final OWLClass CLASS_FORM_LABEL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Form_Label"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Fragment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FRAGMENT.<p>
     * 
     */
    public static final OWLClass CLASS_FRAGMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Fragment"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Fragment_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FRAGMENT_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_FRAGMENT_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Fragment_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Function
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FUNCTION.<p>
     * 
     */
    public static final OWLClass CLASS_FUNCTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Function"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Glass
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GLASS.<p>
     * 
     */
    public static final OWLClass CLASS_GLASS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Glass"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Glass_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GLASS_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_GLASS_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Glass_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Glass_Production_Centre
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GLASS_PRODUCTION_CENTRE.<p>
     * 
     */
    public static final OWLClass CLASS_GLASS_PRODUCTION_CENTRE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Glass_Production_Centre"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Glazed_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GLAZED_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_GLAZED_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Glazed_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Heiligenberg
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HEILIGENBERG.<p>
     * 
     */
    public static final OWLClass CLASS_HEILIGENBERG = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Heiligenberg"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Imitation_Terra_Sigillata_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IMITATION_TERRA_SIGILLATA_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_IMITATION_TERRA_SIGILLATA_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Imitation_Terra_Sigillata_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Inscription
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INSCRIPTION.<p>
     * 
     */
    public static final OWLClass CLASS_INSCRIPTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Inscription"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Inscription_OR_Stamp
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INSCRIPTION_OR_STAMP.<p>
     * 
     */
    public static final OWLClass CLASS_INSCRIPTION_OR_STAMP = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Inscription_OR_Stamp"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Isings
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ISINGS.<p>
     * 
     */
    public static final OWLClass CLASS_ISINGS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Isings"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Ittenweiler
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ITTENWEILER.<p>
     * 
     */
    public static final OWLClass CLASS_ITTENWEILER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Ittenweiler"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Latin_Descriptive_Label
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LATIN_DESCRIPTIVE_LABEL.<p>
     * 
     */
    public static final OWLClass CLASS_LATIN_DESCRIPTIVE_LABEL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Latin_Descriptive_Label"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Ludowici_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LUDOWICI_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_LUDOWICI_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Ludowici_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Maker
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MAKER.<p>
     * 
     */
    public static final OWLClass CLASS_MAKER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Maker"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Material
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MATERIAL.<p>
     * 
     */
    public static final OWLClass CLASS_MATERIAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Material"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Medium_Ceramic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEDIUM_CERAMIC.<p>
     * 
     */
    public static final OWLClass CLASS_MEDIUM_CERAMIC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Medium_Ceramic"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Medium_Ceramic_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEDIUM_CERAMIC_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_MEDIUM_CERAMIC_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Medium_Ceramic_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Metal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METAL.<p>
     * 
     */
    public static final OWLClass CLASS_METAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Metal"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Metal_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METAL_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_METAL_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Metal_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Metal_Production_Centre
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METAL_PRODUCTION_CENTRE.<p>
     * 
     */
    public static final OWLClass CLASS_METAL_PRODUCTION_CENTRE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Metal_Production_Centre"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Middle_Gaul
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MIDDLE_GAUL.<p>
     * 
     */
    public static final OWLClass CLASS_MIDDLE_GAUL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Middle_Gaul"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Mint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MINT.<p>
     * 
     */
    public static final OWLClass CLASS_MINT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Mint"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Mittelbron
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MITTELBRON.<p>
     * 
     */
    public static final OWLClass CLASS_MITTELBRON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Mittelbron"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Niederbieber_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NIEDERBIEBER_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_NIEDERBIEBER_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Niederbieber_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Production_Centre
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRODUCTION_CENTRE.<p>
     * 
     */
    public static final OWLClass CLASS_PRODUCTION_CENTRE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Production_Centre"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Raetia
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RAETIA.<p>
     * 
     */
    public static final OWLClass CLASS_RAETIA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Raetia"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Raetische_Ware_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RAETISCHE_WARE_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_RAETISCHE_WARE_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Raetische_Ware_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Rheinische_Ware
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RHEINISCHE_WARE.<p>
     * 
     */
    public static final OWLClass CLASS_RHEINISCHE_WARE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Rheinische_Ware"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Rheinzabern
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RHEINZABERN.<p>
     * 
     */
    public static final OWLClass CLASS_RHEINZABERN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Rheinzabern"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Schwäbische
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCHWÄBISCHE.<p>
     * 
     */
    public static final OWLClass CLASS_SCHWÄBISCHE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Schwäbische"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Site
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITE.<p>
     * 
     */
    public static final OWLClass CLASS_SITE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Site"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Site_Phase
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITE_PHASE.<p>
     * 
     */
    public static final OWLClass CLASS_SITE_PHASE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Site_Phase"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Skeletal_Material
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SKELETAL_MATERIAL.<p>
     * 
     */
    public static final OWLClass CLASS_SKELETAL_MATERIAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Skeletal_Material"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#South_Gaul
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SOUTH_GAUL.<p>
     * 
     */
    public static final OWLClass CLASS_SOUTH_GAUL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#South_Gaul"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Stamp
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STAMP.<p>
     * 
     */
    public static final OWLClass CLASS_STAMP = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Stamp"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Structure
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STRUCTURE.<p>
     * 
     */
    public static final OWLClass CLASS_STRUCTURE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Structure"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Technik_b
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TECHNIK_B.<p>
     * 
     */
    public static final OWLClass CLASS_TECHNIK_B = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Technik_b"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#TempCategory
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPCATEGORY.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPCATEGORY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#TempCategory"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Terra_Nigra_or_Terra_Nigra_like_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TERRA_NIGRA_OR_TERRA_NIGRA_LIKE_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_TERRA_NIGRA_OR_TERRA_NIGRA_LIKE_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Terra_Nigra_or_Terra_Nigra_like_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Terra_Sigillata_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TERRA_SIGILLATA_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_TERRA_SIGILLATA_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Terra_Sigillata_Form_Type"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Upper_German
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class UPPER_GERMAN.<p>
     * 
     */
    public static final OWLClass CLASS_UPPER_GERMAN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Upper_German"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Utilitarian_Ceramic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class UTILITARIAN_CERAMIC.<p>
     * 
     */
    public static final OWLClass CLASS_UTILITARIAN_CERAMIC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Utilitarian_Ceramic"));

    /* ***************************************************
     * Class http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Utilitarian_Ceramic_Form_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class UTILITARIAN_CERAMIC_FORM_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_UTILITARIAN_CERAMIC_FORM_TYPE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Utilitarian_Ceramic_Form_Type"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Context_contains
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTEXT_CONTAINS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTEXT_CONTAINS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Context_contains"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Structure_contains
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property STRUCTURE_CONTAINS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_STRUCTURE_CONTAINS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Structure_contains"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Artefact-relation_with
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_ARTEFACT_RELATION_WITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_ARTEFACT_RELATION_WITH = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Artefact-relation_with"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Ceramic_Form_Type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_CERAMIC_FORM_TYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_CERAMIC_FORM_TYPE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Ceramic_Form_Type"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Coordinate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_COORDINATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_COORDINATE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Coordinate"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Date_Range
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_DATE_RANGE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_DATE_RANGE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Date_Range"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Form_Label
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_FORM_LABEL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_FORM_LABEL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Form_Label"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Form_Type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_FORM_TYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_FORM_TYPE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Form_Type"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Fragment_Type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_FRAGMENT_TYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_FRAGMENT_TYPE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Fragment_Type"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Function
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_FUNCTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_FUNCTION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Function"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Glass_Form_Type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_GLASS_FORM_TYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_GLASS_FORM_TYPE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Glass_Form_Type"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Inscription_OR_Stamp
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_INSCRIPTION_OR_STAMP.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_INSCRIPTION_OR_STAMP = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Inscription_OR_Stamp"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Latin_Descriptive_Label
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_LATIN_DESCRIPTIVE_LABEL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_LATIN_DESCRIPTIVE_LABEL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Latin_Descriptive_Label"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Stratigraphic_Relation_with
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_STRATIGRAPHIC_RELATION_WITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_STRATIGRAPHIC_RELATION_WITH = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Stratigraphic_Relation_with"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_associated_Artefacts
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_ASSOCIATED_ARTEFACTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_ASSOCIATED_ARTEFACTS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_associated_Artefacts"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_associated_with
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_ASSOCIATED_WITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_ASSOCIATED_WITH = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_associated_with"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_associated_with_Phase
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_ASSOCIATED_WITH_PHASE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_ASSOCIATED_WITH_PHASE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_associated_with_Phase"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_fragmented_in
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_FRAGMENTED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_FRAGMENTED_IN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_fragmented_in"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_inscribed_on
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_INSCRIBED_ON.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_INSCRIBED_ON = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_inscribed_on"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_made_from
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_MADE_FROM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_MADE_FROM = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_made_from"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_overlain_by
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_OVERLAIN_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_OVERLAIN_BY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_overlain_by"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_part_of
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PART_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PART_OF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_part_of"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_part_of_spatial
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PART_OF_SPATIAL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PART_OF_SPATIAL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_part_of_spatial"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_part_of_temporal
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PART_OF_TEMPORAL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PART_OF_TEMPORAL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_part_of_temporal"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_subset_of
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_SUBSET_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_SUBSET_OF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_subset_of"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_superset_of
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_SUPERSET_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_SUPERSET_OF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#is_superset_of"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#made
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MADE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MADE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#made"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#overlays
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OVERLAYS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OVERLAYS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#overlays"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_found_at_Site
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WAS_FOUND_AT_SITE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WAS_FOUND_AT_SITE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_found_at_Site"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_found_in_Archaeological_Context
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WAS_FOUND_IN_ARCHAEOLOGICAL_CONTEXT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WAS_FOUND_IN_ARCHAEOLOGICAL_CONTEXT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_found_in_Archaeological_Context"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_made_by
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WAS_MADE_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WAS_MADE_BY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_made_by"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_produced_at
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WAS_PRODUCED_AT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WAS_PRODUCED_AT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#was_produced_at"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Current_Location
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CURRENT_LOCATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CURRENT_LOCATION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#Current_Location"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#associated_Emperor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ASSOCIATED_EMPEROR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ASSOCIATED_EMPEROR = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#associated_Emperor"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Base_Diameter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_BASE_DIAMETER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_BASE_DIAMETER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Base_Diameter"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Base_Ring_Diameter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_BASE_RING_DIAMETER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_BASE_RING_DIAMETER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Base_Ring_Diameter"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Building_Number
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_BUILDING_NUMBER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_BUILDING_NUMBER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Building_Number"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Building_Phase_GIS_code
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_BUILDING_PHASE_GIS_CODE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_BUILDING_PHASE_GIS_CODE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Building_Phase_GIS_code"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Building_Phase_Number
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_BUILDING_PHASE_NUMBER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_BUILDING_PHASE_NUMBER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Building_Phase_Number"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Catalogue_Number
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_CATALOGUE_NUMBER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_CATALOGUE_NUMBER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Catalogue_Number"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Complex_Number
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_COMPLEX_NUMBER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_COMPLEX_NUMBER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Complex_Number"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Context_Number
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_CONTEXT_NUMBER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_CONTEXT_NUMBER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Context_Number"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Decoration
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_DECORATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_DECORATION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Decoration"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_DESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description_Location
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_DESCRIPTION_LOCATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_DESCRIPTION_LOCATION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description_Location"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description_Material
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_DESCRIPTION_MATERIAL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_DESCRIPTION_MATERIAL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description_Material"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description_preservation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_DESCRIPTION_PRESERVATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_DESCRIPTION_PRESERVATION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Description_preservation"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Diameter_other
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_DIAMETER_OTHER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_DIAMETER_OTHER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Diameter_other"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Dimensions
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_DIMENSIONS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_DIMENSIONS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Dimensions"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Elevation_lower_limit
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_ELEVATION_LOWER_LIMIT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_ELEVATION_LOWER_LIMIT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Elevation_lower_limit"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Elevation_upper_limit
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_ELEVATION_UPPER_LIMIT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_ELEVATION_UPPER_LIMIT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Elevation_upper_limit"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_End_Date
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_END_DATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_END_DATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_End_Date"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_GIS_code_information
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_GIS_CODE_INFORMATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_GIS_CODE_INFORMATION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_GIS_code_information"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Glaze
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_GLAZE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_GLAZE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Glaze"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Height
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_HEIGHT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_HEIGHT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Height"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Image_URL
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_IMAGE_URL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_IMAGE_URL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Image_URL"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Inscription_catalogue_number
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_INSCRIPTION_CATALOGUE_NUMBER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_INSCRIPTION_CATALOGUE_NUMBER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Inscription_catalogue_number"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Length
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_LENGTH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_LENGTH = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Length"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Lower_X_Coordinate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_LOWER_X_COORDINATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_LOWER_X_COORDINATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Lower_X_Coordinate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Lower_Y_Coordinate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_LOWER_Y_COORDINATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_LOWER_Y_COORDINATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Lower_Y_Coordinate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Painted_Decoration
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_PAINTED_DECORATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_PAINTED_DECORATION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Painted_Decoration"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Provenance_Code
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_PROVENANCE_CODE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_PROVENANCE_CODE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Provenance_Code"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Reference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_REFERENCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_REFERENCE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Reference"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Relief_Decoration
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_RELIEF_DECORATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_RELIEF_DECORATION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Relief_Decoration"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Rim_Diameter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_RIM_DIAMETER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_RIM_DIAMETER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Rim_Diameter"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Site_Phase_Number
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_SITE_PHASE_NUMBER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_SITE_PHASE_NUMBER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Site_Phase_Number"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Start_Date
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_START_DATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_START_DATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Start_Date"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Surface_Treatment
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_SURFACE_TREATMENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_SURFACE_TREATMENT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Surface_Treatment"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Thickness
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_THICKNESS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_THICKNESS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Thickness"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Uncertainty_Note
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_UNCERTAINTY_NOTE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_UNCERTAINTY_NOTE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Uncertainty_Note"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Upper_X_Coordinate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_UPPER_X_COORDINATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_UPPER_X_COORDINATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Upper_X_Coordinate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Upper_Y_Coordinate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_UPPER_Y_COORDINATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_UPPER_Y_COORDINATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Upper_Y_Coordinate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Use_Wear
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_USE_WEAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_USE_WEAR = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_Use_Wear"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_breadth
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_BREADTH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_BREADTH = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_breadth"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_colour
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_COLOUR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_COLOUR = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_colour"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_identity_Label
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_IDENTITY_LABEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_IDENTITY_LABEL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_identity_Label"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_preserved_Height
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_PRESERVED_HEIGHT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_PRESERVED_HEIGHT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_preserved_Height"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_restoration_evidence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_RESTORATION_EVIDENCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_RESTORATION_EVIDENCE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_restoration_evidence"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_surrounding_material
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_SURROUNDING_MATERIAL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_SURROUNDING_MATERIAL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_surrounding_material"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_weight
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_WEIGHT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_WEIGHT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#has_weight"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#number_of_fragments
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NUMBER_OF_FRAGMENTS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NUMBER_OF_FRAGMENTS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#number_of_fragments"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#source_for_Date_Range
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SOURCE_FOR_DATE_RANGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SOURCE_FOR_DATE_RANGE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#source_for_Date_Range"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#type_of_Archaeological_Context
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TYPE_OF_ARCHAEOLOGICAL_CONTEXT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TYPE_OF_ARCHAEOLOGICAL_CONTEXT = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#type_of_Archaeological_Context"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#type_of_fragments
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TYPE_OF_FRAGMENTS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TYPE_OF_FRAGMENTS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/daan/ontologies/2016/3/BDRTontology#type_of_fragments"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
